# Generated by Django 4.0.3 on 2022-04-11 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Department name')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name="Employee's id")),
                ('name', models.CharField(max_length=50, verbose_name='Employee name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name="employee's email")),
                ('join_date', models.DateField(verbose_name="Employee's join date")),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department', verbose_name='Employee department')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manger', to='department.employee', verbose_name="Department's Manger"),
        ),
    ]
