# Generated by Django 4.0.3 on 2022-04-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_alter_department_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Famale')], default='----------', max_length=50, verbose_name="Employee's gender"),
        ),
    ]
